name: Build Windows x64

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Use Node.js version
        uses: actions/setup-node@v1
        with:
        node-version: 12.2.0

      - name: Build
        run: |
          npm ci
          npm test
          npm run build-windows-x64

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./egm
          asset_name: egm-windows-x64
          asset_content_type: application/x-executable; charset=binary

